ERROR - 2024-07-11 10:54:05 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/system/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /var/www/system/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('mysql:3390', 'root', Object(SensitiveParameterValue), 'pec_permintaanm...', 3306, '', 0)
#1 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/system/vendor/codeigniter4/framework/system/Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/system/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/system/app/Controllers/Auth.php(17): CodeIgniter\BaseModel->findAll()
#7 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(942): App\Controllers\Auth->index()
#8 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/system/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/system/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/system/vendor/codeigniter4/framework/system/Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/system/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/system/app/Controllers/Auth.php(17): CodeIgniter\BaseModel->findAll()
#6 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(942): App\Controllers\Auth->index()
#7 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 /var/www/system/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-07-11 10:54:05 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
ORDER BY `username` ASC', [], false)
 3 SYSTEMPATH/Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Auth.php(17): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Auth->index()
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
